### PR TITLE
Console::collect DRYs up #console

### PR DESCRIPTION
**Pull request by dacamp**
10th question use case

### CODE REVIEW

**Comment by dacamp** [comment]
Thanks for this repo, it's a **really** clever idea.  I think I've fixed a minor sorting bug, let me know what you think.

`Dir[path]` does not sort the array.  Added the `Console::collect` method to dry things up; admittedly not by much.

#### Before

``` lang=ruby
[1] pry(#<Console::Question>)> Dir["#{Rails.root}/lib/#{@dir}/**/*.rb"]
=> ["/Users/dcam/git/interview/lib/questions/0.rb",
 "/Users/dcam/git/interview/lib/questions/1.rb",
 "/Users/dcam/git/interview/lib/questions/10.rb",
 "/Users/dcam/git/interview/lib/questions/2.rb",
 "/Users/dcam/git/interview/lib/questions/3.rb",
 "/Users/dcam/git/interview/lib/questions/4.rb",
 "/Users/dcam/git/interview/lib/questions/5.rb",
 "/Users/dcam/git/interview/lib/questions/6.rb",
 "/Users/dcam/git/interview/lib/questions/7.rb",
 "/Users/dcam/git/interview/lib/questions/8.rb",
 "/Users/dcam/git/interview/lib/questions/9.rb"]
```

#### After

``` lang=ruby
[5] pry(#<Console::Question>)> Dir["#{Rails.root}/lib/#{@dir}/**/*.rb"].sort_by{ |x| x[/\d+/].to_i }
=> ["/Users/dcam/git/interview/lib/questions/0.rb",
 "/Users/dcam/git/interview/lib/questions/1.rb",
 "/Users/dcam/git/interview/lib/questions/2.rb",
 "/Users/dcam/git/interview/lib/questions/3.rb",
 "/Users/dcam/git/interview/lib/questions/4.rb",
 "/Users/dcam/git/interview/lib/questions/5.rb",
 "/Users/dcam/git/interview/lib/questions/6.rb",
 "/Users/dcam/git/interview/lib/questions/7.rb",
 "/Users/dcam/git/interview/lib/questions/8.rb",
 "/Users/dcam/git/interview/lib/questions/9.rb",
 "/Users/dcam/git/interview/lib/questions/10.rb"]
```

My 10th question is uninspired, so if you'd prefer I can drop it from the PR.

**Comment by adlerhsieh** [comment]
I agree with the idea of `collect`.

I can see the trick in the 10th question but maybe that's not a great fit in this repo (as an example for other interviewers to design their own questions). Maybe remove it in this PR and we can discuss it in another. Thanks!

**Comment by dacamp** [comment]
I agree, my new question sucked. :)  I've force pushed to remove it.

**Comment by adlerhsieh** [comment]
Thanks!

**Pull request merged**
